<h1>Data Science</h1>

<p>Sean has taken a number of Coursera courses offered through Johns Hopkins University. Below is a list detailing courses
related to Data Science that Sean has taken; clicking on the course name will take you to the associated course certificate
</p>
<br>
<ul>
    <li>
        <p>
        <a href="https://www.coursera.org/account/accomplishments/records/TuTqNSHWURgjrQV3">R Programming</a> -
        This was a course on R programming which covered aspects of the language which would be necessary for work with
            Data Science exercises. One of the programming assignments was to leverage the lexical scoping of the R
            programming language to cache an inverted matrix. Below are links to Github pages detailing the assignment and
            Sean's submission for the assignment.
            <br>
            <b>Assignment:</b> <a href="https://github.com/dunagan5887/ProgrammingAssignment2#assignment-caching-the-inverse-of-a-matrix">Caching the Inverse of a Matrix</a>
            <br>
            <b>Sean's Submission:</b> <a href="https://github.com/dunagan5887/ProgrammingAssignment2/blob/master/cachematrix.R">cachematrix.R</a>
        </p>
    </li>
    <br>
    <li>
        <a href="https://www.coursera.org/account/accomplishments/records/wZAZyBxcKQFyFCZX">Statistical Inference</a> -
        This course covered basic Statistical Inference topics relevant to Data Science practices. It covered various statistical distributions
        and their use-cases.<br>
        Below is a link to an assignment for this course. It involved discussing the difference between distributions of samples and
        distributions of sample average. The assignment contained a write-up as well as writing R code to generate the sample data.<br>
        <b>Assignment Submission:</b> <a href="https://github.com/dunagan5887/Coursera_Projects/blob/master/statistical_inference_distribution_of_sample_averages.pdf">Disribution of Sample Averages</a>
        <br>
        Another assignment involved comparing samples between two groups of test subjects. The assignment involved generating T-confidence intervals
        and evaluating hypothesis according to the intervals.
        <br>
        <b>Assignment Submission:</b> <a href="https://github.com/dunagan5887/Coursera_Projects/blob/master/statistical_inference_toothgrowth_analysis.pdf">Confidence Interval Analysis</a>
    </li>
    <br>
    <li>
        <a href="https://www.coursera.org/account/accomplishments/records/5thEqBwc7d6GCR3x">Regression Models</a> -
        This was an introductory course to Regression Models and interpreting their coefficients. The course project for this course involved
        comparing a set of cars, some with manual transmissions and others with automatic transmissions. The goal of the project was to determine
        whether having a manual or automatic transmission lead to better MPG, and by how much. Below is a link to the Github directory containing
        Sean's submission for the assignment. File <a href="https://github.com/dunagan5887/datasciencecoursera/blob/master/regression_models_course_project/mpg_against_transmission.pdf">mpg_against_transmission.pdf</a>
        contains the formal writeup for the assignment. File <a href="https://github.com/dunagan5887/datasciencecoursera/blob/master/regression_models_course_project/course_project.R">course_project.R</a>
        contains Sean's R code used in the generation of the charts and figures for the assignment.<br>
        <b>Assignment Submission:</b><a href="https://github.com/dunagan5887/datasciencecoursera/tree/master/regression_models_course_project">Course Project</a>
    </li>
    <br>
    <li>
        <a href="https://www.coursera.org/account/accomplishments/records/KEMvWYsPPqgtUANM">Exploratory Data Analysis</a> -
        This was an introductory course into Exploratory Data Analysis involving plotting data sets. The course project essentially
        consisted of creating several graphs from data. While not an overly complex project, Sean's submission for the project is linked
        below:<br>
        <b>Assignment Submission:</b><a href="https://github.com/dunagan5887/datasciencecoursera/tree/master/exploratory_data_analysis/course_project_2">Course Project</a>
    </li>
</ul>