<h1>Spark</h1>

<p>
    To gain experience working with the Python programming language and the Spark framework, Sean has produced a code
    sample implementing both which can be viewed at
    <a href="https://github.com/dunagan5887/machine_learning">https://github.com/dunagan5887/machine_learning</a><br>
    <br>
    The code sample consists of two projects which are detailed in the README.md file in the repository.
    The main project's focus was to cluster stocks based on their performance in the past year. The Spark
    MLLib KMeans.train() function was used to cluster the stocks. While the raw data was downloaded from Yahoo Finance's
    Historical Prices site in PHP, the rest of the project was written in Python. While reviewing the code, please keep
    in mind that this project was written primarily as a code sample, not as a production-environment worthy long-term
    codebase.<br>
    <br>
    The results of the project can be seen at the website below:<br>
        <a href="http://demo.developer-magento.com/admin">http://demo.developer-magento.com/admin</a><br>
        User Name: demo_admin<br>
        Password: demo123<br>
    Once you are logged in to the Magento admin panel, navigate to Stocks -> Stock Clusters -> View Stock Cluster Centers.<br>
    <br>
    This project is covered in more detail at the Github repository url given above. The repository contains the
    code-set and a README.md file which covers the project in a bit more detail.
</p>