<?php /* @var $this Worldview_Article_Block_Table_Row */ ?>

<?php $articleToDisplay = $this->getArticleToDisplay(); ?>

<?php
/*
 * @TODO
 * This template file needs to create the html necessary to show each row of the table. $articleToDisplay refers to the
 *  article which should be displayed
 *
 * As an example, below is an example of how to access the `title` data field of the $articleToDisplay object
 */

$article_title = $articleToDisplay->getTitle();
?>

