<h1>Machine Learning and Data Science Portfolio</h1>

<p>To prepare for a career in Machine Learning and Data Science, Sean has put together a portfolio of projects
to gain experience in these fields. Sean took a number of the Data Science courses instructed by Johns Hopkins
University through Coursera. Additionally, Sean engaged in a couple of personal projects involving Spark to gain
experience with that framework. Below are links to pages containing more detail regarding these projects.</p>
<br>
<ul>
    <li><a href="http://www.seandunagan.com/dunagan_portfolio/DataScience">Data Science Projects</a></li>
    <li><a href="http://www.seandunagan.com/dunagan_portfolio/spark">Spark Projects</a></li>
</ul>
